development:
  adapter: mysql2
  host: localhost
  database: monster_drink_development
  username: root
  password:

test:
  adapter: mysql2
  host: localhost
  database: monster_drink_production
  username: root
  password:
